### ISSUE TITLE
Installing requirements.txt facing problem in python 3.12.0

### ISSUE THREAD

**Issue by mmar58** [Cryoscopic-E/PDSim-Backend#2]
Hi,
first I followed [this instrctions](https://github.com/Cryoscopic-E/PDSim/wiki/Installation) and ran `pip install unified-planning[engines] pyzmq requests` and installed successfully.
Then I clone this repo and ran 'python -m pip install -r requirements.txt'.

But it's showing this error
`Requirement already satisfied: pyzmq~=25.1.1 in c:\python312\lib\site-packages (from -r requirements.txt (line 1)) (25.1.1)
Requirement already satisfied: requests~=2.31.0 in c:\python312\lib\site-packages (from -r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: protobuf in c:\python312\lib\site-packages (from -r requirements.txt (line 3)) (4.21.12)
Collecting unified-planning==1.0.0 (from -r requirements.txt (line 4))
  Using cached unified_planning-1.0.0-py3-none-any.whl.metadata (2.8 kB)
Collecting up-fast-downward==0.3.1 (from -r requirements.txt (line 5))
  Using cached up_fast_downward-0.3.1-py3-none-win_amd64.whl.metadata (836 bytes)
Collecting up-tamer (from -r requirements.txt (line 6))
  Using cached up_tamer-1.0.0-py3-none-any.whl.metadata (266 bytes)
ERROR: Ignored the following yanked versions: 0.0.1, 0.0.4.0, 0.0.4.1
ERROR: Could not find a version that satisfies the requirement up-lpg (from versions: none)
ERROR: No matching distribution found for up-lpg
`

Please let me know, how to fix it

**Comment by Cryoscopic-E** [comment]
Hi! That's a problem with the python library this tool is using not finding the correct version for the lpg planner.

If you clone the repo this comes with the requirements file here:https://github.com/Cryoscopic-E/PDSim-Backend/blob/main/requirements.txt

Simply install via `pip install -r requirements.txt`

Cheers!

**Comment by mmar58** [comment]
I found out that this problem is with python 3.12 version. I have installed python 3.11.6 and it worked fine
